//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_policy
    {
        public long policyid { get; set; }
        public int aon_id { get; set; }
        public long stagid { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public string Remarks { get; set; }
        public string pdfattachment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> section_id { get; set; }
    
        public virtual tbl_mst_Template tbl_mst_Template { get; set; }
        public virtual acq_project_master acq_project_master { get; set; }
        public virtual acq_project_master acq_project_master1 { get; set; }
        public virtual acq_project_master acq_project_master2 { get; set; }
    }
}
