//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_project_status_1
    {
        public int project_id { get; set; }
        public int task_id { get; set; }
        public Nullable<int> planned_start_date { get; set; }
        public Nullable<int> planned_end_date { get; set; }
        public Nullable<int> actual_start_date { get; set; }
        public Nullable<System.DateTime> actual_end_date { get; set; }
    }
}
