//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_meeting_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acq_meeting_master()
        {
            this.acq_project_master = new HashSet<acq_project_master>();
        }
    
        public int meeting_id { get; set; }
        public string dac_dpb { get; set; }
        public Nullable<System.DateTime> meeting_date { get; set; }
        public Nullable<System.DateTime> Date_of_Issue_of_Minutes { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string Remarks { get; set; }
        public string officers_participated { get; set; }
        public string Distribution_List { get; set; }
        public string Meeting_Number { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acq_project_master> acq_project_master { get; set; }
    }
}
