//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_projectstage_applicability
    {
        public int Id { get; set; }
        public Nullable<int> AoN { get; set; }
        public string stage { get; set; }
        public string applicable { get; set; }
        public string Remarks { get; set; }
    }
}
