//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_project_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acq_project_master()
        {
            this.acq_policy = new HashSet<acq_policy>();
        }
    
        public int aon_id { get; set; }
        public string item_description { get; set; }
        public string DPP_DAP { get; set; }
        public string AoN_Accorded_By { get; set; }
        public Nullable<System.DateTime> Date_of_Accord_of_AoN { get; set; }
        public Nullable<int> meeting_id { get; set; }
        public string Categorisation { get; set; }
        public string Service_Lead_Service { get; set; }
        public string Quantity { get; set; }
        public string Cost { get; set; }
        public string Currency { get; set; }
        public string Tax_Duties { get; set; }
        public string Type_of_Acquisition { get; set; }
        public string Trials_Required { get; set; }
        public string Essential_parameters { get; set; }
        public string Any_other_aspect { get; set; }
        public string IC_percentage { get; set; }
        public string Option_clause_applicable { get; set; }
        public string Offset_applicable { get; set; }
        public string AMC_applicable { get; set; }
        public string AMCRemarks { get; set; }
        public string Warrenty_applicable { get; set; }
        public string Warrenty_Remarks { get; set; }
        public string AoN_validity { get; set; }
        public string AoN_validity_unit { get; set; }
        public Nullable<decimal> AoN_revalidation_meeting_id { get; set; }
        public Nullable<System.DateTime> AoN_validity_extended_till { get; set; }
        public Nullable<decimal> AoN_Foreclosure_meeting_id { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> AoNClosureDate { get; set; }
        public string AoNClosureRemarks { get; set; }
        public Nullable<int> AoNForeClosureCreatedBy { get; set; }
        public string VendorsIDs { get; set; }
        public Nullable<int> DirectorateId { get; set; }
        public string ResponsiblePersonLeve1 { get; set; }
        public string ResponsiblePersonLeve2 { get; set; }
        public string ResponsiblePersonLeve3 { get; set; }
        public string ResponsiblePersonLeve4 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string System_case { get; set; }
    
        public virtual acq_meeting_master acq_meeting_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acq_policy> acq_policy { get; set; }
    }
}
