//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_section_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acq_section_master()
        {
            this.tbl_tbl_User = new HashSet<tbl_tbl_User>();
        }
    
        public int section_id { get; set; }
        public string section_descr { get; set; }
        public Nullable<int> deptt_id { get; set; }
        public Nullable<int> ServiceType { get; set; }
    
        public virtual acq_department_master acq_department_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tbl_User> tbl_tbl_User { get; set; }
    }
}
