//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_rfp_VendorsDetails
    {
        public int ID { get; set; }
        public int rfpID { get; set; }
        public int vendor_id { get; set; }
        public Nullable<byte> type_ID { get; set; }
    
        public virtual tbl_tblVendor tbl_tblVendor { get; set; }
    }
}
