//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_rfp_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acq_rfp_master()
        {
            this.acq_rfp_vendors = new HashSet<acq_rfp_vendors>();
        }
    
        public int rfp_id { get; set; }
        public int aon_id { get; set; }
        public string type_rfp { get; set; }
        public string draft_rfp_date { get; set; }
        public string date_submissionto_adgacq { get; set; }
        public string date_acceptanceby_adgacq { get; set; }
        public string date_collegiate_vetting { get; set; }
        public string date_approval_rfp { get; set; }
        public string date_issue_rfp { get; set; }
        public string date_prebid_meeting { get; set; }
        public string date_prebid_replies { get; set; }
        public string lastdate_bidsubmission { get; set; }
        public string date_bid_opening { get; set; }
        public string ExtendedLastDate_BidSubmission { get; set; }
        public string date_tec_constitution { get; set; }
        public string date_tec_commencement { get; set; }
        public string date_tec_completion { get; set; }
        public string date_tec_reportsubmission { get; set; }
        public string date_tec_approval { get; set; }
        public string date_submission_eut { get; set; }
        public string date_issue_trials_directive { get; set; }
        public string Date_received_Fet { get; set; }
        public string Date_accepted_Fet { get; set; }
        public string Date_toc_Constitution { get; set; }
        public string Date_toc_report { get; set; }
        public string Date_toc_acceptance_CompetantAuth { get; set; }
        public string Date_cnc_constitution { get; set; }
        public string Date_cnc_benchmarking { get; set; }
        public string Date_commercial_bid_opening { get; set; }
        public string Date_cnc_conclusion { get; set; }
        public string Date_cnc_report { get; set; }
        public string date_Submission_CFANote_DGacq { get; set; }
        public string date_Acq_approvalforsending_to_MoDFin { get; set; }
        public string date_submissionto_CFA { get; set; }
        public string date_Approval_CFAnote { get; set; }
        public string date_DCN_Sentfor_InterMinisterialConsultations { get; set; }
        public string date_MoF_Concurrence { get; set; }
        public string date_DCN_submissionto_CCS { get; set; }
        public string ApproveToCSS_CFA { get; set; }
        public string DateContractSigning { get; set; }
        public string date_approval_CFA_CCS { get; set; }
        public string date_ContractSigning { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Eoi_DPRDateIssueMakeI { get; set; }
        public string Eoi_DPRReceiptDateMakeI { get; set; }
        public string Eoi_DPRDateCompletionandResponseMakeI { get; set; }
        public string dtforwardingshortlistedDPMakeI { get; set; }
        public string dateapprovalshortlistedvendorsMakeI { get; set; }
        public string DateIssueMake_II { get; set; }
        public string EoiReceiptDateMake_II { get; set; }
        public string EoiCompletionResponseMake_II { get; set; }
        public string dateApprovalEoiMake_II { get; set; }
        public string dateissueProjectSenctionMake_II { get; set; }
        public string dateFormulationJPMT_DD { get; set; }
        public string dateFormulationPMT_DD { get; set; }
        public string dateIdentificationDCPP_DD { get; set; }
        public string datedetaildesignbySHQ_DD { get; set; }
        public string dateissuetrialdeveiation_DD { get; set; }
        public string dateprojectReview_DD { get; set; }
        public string daterealisationPrototype_DD { get; set; }
        public string dateCommencementPSQR { get; set; }
        public string dateCulminationPSQRValid_DD { get; set; }
        public string dateselectionDasbySHQ_dprbMakeI { get; set; }
        public string dateapprovalCFAfundingarrangementissueProjectMakeI { get; set; }
        public string datecommencementpreliminaryMakeI { get; set; }
        public string datefinalisationdetaileddesign { get; set; }
        public string datecommencementfabrication_devProMakeI { get; set; }
        public string datetechnicallimitedfieldstrialsMakeI { get; set; }
        public string datefreezingPSQRStoSQRSMakeI { get; set; }
        public string dateintimationvendorssubmissionrevisedMakeI { get; set; }
        public string datesubmissionrevisedcommercialoffersvendorsMakeI { get; set; }
        public string datecommencementDevPrototypeMakeII { get; set; }
        public string datecompletionDevPrototypeMakeII { get; set; }
        public string datecommencementUserTrialsMakeII { get; set; }
        public string datecompletionUserTrialsRedinessReviewMakeII { get; set; }
        public string dateFreezingPSQRsMakeII { get; set; }
        public string dateselectionDasbySHQ_dprbMakeII { get; set; }
        public string dateapprovalCFAfundingarrangementissueProjectMakeII { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acq_rfp_vendors> acq_rfp_vendors { get; set; }
    }
}
