//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_audit_trail
    {
        public int LogId { get; set; }
        public string UserEmail { get; set; }
        public string IPAddress { get; set; }
        public string Action { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Restime { get; set; }
        public string IsActive { get; set; }
    }
}
