//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acq_rfp_vendors
    {
        public int rfp_id { get; set; }
        public int Rfp_fk_Id { get; set; }
    
        public virtual acq_rfp_master acq_rfp_master { get; set; }
    }
}
