//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    
    public partial class PROC_DASHBOARD_First_CountGrid_Result1
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> BF { get; set; }
        public Nullable<int> Cases { get; set; }
        public Nullable<int> Casesdisposed { get; set; }
        public Nullable<int> Outstanding { get; set; }
    }
}
