//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_WiseReport
    {
        public long Pkey { get; set; }
        public string pending_in_stage { get; set; }
        public Nullable<int> n_projects { get; set; }
        public Nullable<decimal> total_aon_cost { get; set; }
    }
}
