//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_tryProject1
    {
        public long TryPojectID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Template_type { get; set; }
        public Nullable<decimal> taskslno { get; set; }
        public string taskdescription { get; set; }
        public string shortname { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string Dependencies { get; set; }
        public string super_task_id { get; set; }
        public Nullable<long> responsibilitydepart { get; set; }
        public Nullable<long> Responsibility { get; set; }
        public string isactive { get; set; }
        public int progress { get; set; }
        public Nullable<System.DateTime> planned_start_date { get; set; }
        public Nullable<System.DateTime> planned_end_date { get; set; }
    }
}
