//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Master_Role
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> FormMenuID { get; set; }
        public string FormName { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
