//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_master_formMenu
    {
        public int ID { get; set; }
        public string From_menu { get; set; }
        public string ActionName { get; set; }
        public string Controller { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
        public Nullable<int> MenuId { get; set; }
    }
}
