//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tblVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_tblVendor()
        {
            this.acq_rfp_VendorsDetails = new HashSet<acq_rfp_VendorsDetails>();
        }
    
        public int VendorId { get; set; }
        public int VendorCategory { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public string VendorContactName { get; set; }
        public string VendorPhone { get; set; }
        public string VendorEmail { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual tbl_tblVendorCategory tbl_tblVendorCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acq_rfp_VendorsDetails> acq_rfp_VendorsDetails { get; set; }
    }
}
