//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tbl_User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string InternalEmailID { get; set; }
        public string ExternalEmailID { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTill { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<int> ReportingTo { get; set; }
        public string Designation { get; set; }
        public string RankUser { get; set; }
        public string LoginAllowed { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Pswd_Salt { get; set; }
        public string Flag { get; set; }
        public string Temp_Number { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<System.DateTime> ExpiryTime { get; set; }
        public string TokenId { get; set; }
        public string DSCSerialno { get; set; }
    
        public virtual acq_department_master acq_department_master { get; set; }
        public virtual acq_section_master acq_section_master { get; set; }
    }
}
