//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_UpdateStausDummy
    {
        public long UpdateStatusTaskId { get; set; }
        public Nullable<long> TryPojectID { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string TaskSlno { get; set; }
        public Nullable<System.DateTime> PlannStartDate { get; set; }
        public Nullable<System.DateTime> PlannEndDate { get; set; }
        public Nullable<System.DateTime> ActuaStartDate { get; set; }
        public Nullable<System.DateTime> ActuaEndDate { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
    }
}
