//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_BF
    {
        public decimal id { get; set; }
        public int BF { get; set; }
        public Nullable<int> Cases { get; set; }
        public Nullable<int> Casesdisposed { get; set; }
        public Nullable<int> Outstanding { get; set; }
    }
}
