//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_dashboard
    {
        public decimal TaskSlno { get; set; }
        public Nullable<int> nProject { get; set; }
        public string ShortName { get; set; }
        public string TaskDescription { get; set; }
        public string color { get; set; }
    }
}
