//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_dashboardproject
    {
        public int ProjectId { get; set; }
        public string item_description { get; set; }
        public string categorisation { get; set; }
        public string service { get; set; }
        public Nullable<System.DateTime> AoNDate { get; set; }
        public Nullable<System.DateTime> scheduled_date_of_completion { get; set; }
        public Nullable<int> actual_no_of_days { get; set; }
        public Nullable<int> scheduled_no_of_days { get; set; }
        public Nullable<decimal> percent_delay { get; set; }
    }
}
