//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Chart2
    {
        public long IdPrimaryKey { get; set; }
        public string Categorisation { get; set; }
        public Nullable<int> no_of_projects { get; set; }
    }
}
