//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GridFirst
    {
        public long IdPrimaryKey { get; set; }
        public Nullable<decimal> task_id { get; set; }
        public string taskDescription { get; set; }
        public Nullable<int> avg_delay_days { get; set; }
    }
}
